### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by damb** [savage13/miniseed#3]
Hi there,

what's the current status of this project? Are you planning to implement a feature complete safe interface?

**Comment by jnuss** [comment]
@acarapetis I recall you showing an interest in maintaining `libmseed-sys` and this crate at one point. I'm wondering if you can comment on the status of the project as a whole. Is it safe and suitable as a dependency in new projects? It seems like this crate just needs some further interface implementation of the existing FFI provided by `libmseed-sys` to be more complete.

**Comment by damb** [comment]
@jnuss, since I didn't receive any response, I decided to continue working on this fork of [libmseed-sys](https://github.com/damb/libmseed-sys). Once my recent changes are merged, it would be pretty much ready to go.

Also, for the time being it would be ok for me to maintain a version of the `libmseed-sys` crate. Alternatively, I could help somebody out.

**Comment by jnuss** [comment]
Thanks @damb for taking this on. I'm looking for some support for _writing_ records but the higher-level `miniseed` crate doesn't seem to have any. Can the `libmseed-sys` crate be used directly for this, or is it recommended to add a new implementation in the `miniseed` crate instead?

**Comment by damb** [comment]
I'm still fairly new to Rust. However, usually implementing a safe interface on top of a `-sys` crate is the way to go. This way the `unsafe` code is hidden by the safe interface and the client code isn't cluttered with `unsafe` blocks.

Originally, I was hoping that this crate here (i.e. `miniseed`) would implement a feature complete interface. Though, since I didn't receive any response and this crate here still seems to be a draft implementation I started to work on another implementation. I didn't make it public yet and it is still missing a lot of features. However, if you give me a few days I could both make it public and help you with implementing the writing facilities.

@jnuss, would this help you?

**Comment by jnuss** [comment]
@damb thank you for the offer to help with the writing functionality. It seems that previous `miniseed` crates/repos have been abandoned so it makes sense to proceed with a new fork and add functionality as needed. I am happy to assist too but have limited experience with FFI/safe wrapper interfaces.

**Comment by damb** [comment]
Ok. I updated the [libmseed-sys fork](https://github.com/damb/libmseed-sys). Besides, I made the safe interface I was working on public: https://github.com/damb/mseed. Let's continue any discussions in the dedicated repos.
